import * as fsp from "fs/promises"
import * as fs from "fs"
import * as os from "os"
import * as path from "path"
import { runFmtk, runProcess } from "./process-utils.js"
import type { AutoStartConfig } from "../types/config.js"
import { CliError } from "./cli-error.js"
import type { ModConfig } from "./config/index.js"

export function readDataPath(platform: NodeJS.Platform = os.platform()): string {
  return platform === "darwin" ? "__PATH__executable__/../data" : "__PATH__executable__/../../data"
}

export async function ensureConfigIni(dataDir: string): Promise<void> {
  const filePath = path.join(dataDir, "config.ini")
  if (!fs.existsSync(filePath)) {
    console.log("Creating config.ini file")
    await fsp.writeFile(
      filePath,
      `; This file was auto-generated by factorio-test cli

[path]
read-data=${readDataPath()}
write-data=${dataDir}

[general]
locale=
`,
    )
  } else {
    const content = await fsp.readFile(filePath, "utf8")
    const newContent = content.replace(/^write-data=.*$/m, `write-data=${dataDir}`)
    if (content !== newContent) {
      await fsp.writeFile(filePath, newContent)
    }
  }
}

export type RunMode = "headless" | "graphics"

export function buildAutoStartConfig(modToTest: string, mode: RunMode, lastFailedTests?: string[]): AutoStartConfig {
  return {
    mod: modToTest,
    headless: mode === "headless",
    ...(lastFailedTests?.length && { last_failed_tests: lastFailedTests }),
  }
}

type SettingScope = "startup" | "runtime-global"

const AUTO_START_CONFIG_SETTING = "factorio-test-auto-start-config"
const AUTO_START_SETTING = "factorio-test-auto-start"
const TEST_CONFIG_SETTING = "factorio-test-config"
const MOD_TO_TEST_SETTING = "factorio-test-mod-to-test"

function setModSetting(modsDir: string, scope: SettingScope, name: string, value: string): Promise<void> {
  return runFmtk("settings", "set", scope, name, value, "--modsPath", modsDir)
}

function unsetModSetting(modsDir: string, scope: SettingScope, name: string): Promise<void> {
  return runFmtk("settings", "unset", scope, name, "--modsPath", modsDir)
}

export async function setTestConfigSetting(modsDir: string, testConfig: ModConfig): Promise<void> {
  if (Object.keys(testConfig).length === 0) return
  await setModSetting(modsDir, "runtime-global", TEST_CONFIG_SETTING, JSON.stringify(testConfig))
}

export function setModToTestSetting(modsDir: string, modToTest: string): Promise<void> {
  return setModSetting(modsDir, "runtime-global", MOD_TO_TEST_SETTING, modToTest)
}

export async function ensureModSettingsDat(
  factorioPath: string,
  dataDir: string,
  modsDir: string,
  verbose?: boolean,
): Promise<void> {
  const settingsDat = path.join(modsDir, "mod-settings.dat")
  if (fs.existsSync(settingsDat)) return

  if (verbose) console.log("Creating mod-settings.dat file by running factorio")
  const dummySaveFile = path.join(dataDir, "____dummy_save_file.zip")
  await runProcess(
    false,
    factorioPath,
    "--create",
    dummySaveFile,
    "--mod-directory",
    modsDir,
    "-c",
    path.join(dataDir, "config.ini"),
  )

  if (fs.existsSync(dummySaveFile)) {
    await fsp.rm(dummySaveFile)
  }
}

export interface AutorunOptions {
  verbose?: boolean
  lastFailedTests?: string[]
}

export async function setSettingsForAutorun(
  factorioPath: string,
  dataDir: string,
  modsDir: string,
  modToTest: string,
  mode: RunMode,
  options?: AutorunOptions,
): Promise<void> {
  await ensureModSettingsDat(factorioPath, dataDir, modsDir, options?.verbose)
  if (options?.verbose) console.log("Setting autorun settings")
  const autoStartConfig = buildAutoStartConfig(modToTest, mode, options?.lastFailedTests)
  await setModSetting(modsDir, "startup", AUTO_START_CONFIG_SETTING, JSON.stringify(autoStartConfig))
  await unsetModSetting(modsDir, "startup", AUTO_START_SETTING)
}

export async function resetAutorunSettings(modsDir: string, verbose?: boolean): Promise<void> {
  if (verbose) console.log("Disabling auto-start settings")
  await setModSetting(modsDir, "startup", AUTO_START_CONFIG_SETTING, "{}")
  await setModSetting(modsDir, "runtime-global", TEST_CONFIG_SETTING, "{}")
}

export interface ModWatchTarget {
  type: "directory" | "file"
  path: string
}

export async function resolveModWatchTarget(
  modsDir: string,
  modPath?: string,
  modName?: string,
): Promise<ModWatchTarget> {
  if (modPath) {
    return { type: "directory", path: path.resolve(modPath) }
  }

  const files = await fsp.readdir(modsDir)
  for (const file of files) {
    const fullPath = path.join(modsDir, file)
    const fileStat = await fsp.lstat(fullPath).catch(() => undefined)
    if (!fileStat) continue

    const isDirectoryMatch =
      fileStat.isDirectory() || fileStat.isSymbolicLink()
        ? file === modName || file.match(new RegExp(`^${modName}_\\d+\\.\\d+\\.\\d+$`))
        : false

    if (isDirectoryMatch) {
      const targetPath = fileStat.isSymbolicLink() ? await fsp.realpath(fullPath) : fullPath
      return { type: "directory", path: targetPath }
    }

    const isFileMatch = fileStat.isFile()
      ? file === modName + ".zip" || file.match(new RegExp(`^${modName}_\\d+\\.\\d+\\.\\d+\\.zip$`))
      : false

    if (isFileMatch) {
      return { type: "file", path: fullPath }
    }
  }

  throw new CliError(`Could not find mod ${modName} in ${modsDir} for watching`)
}
